### ISSUE TITLE
[BUG] "default" is not exported by "node_modules/@chakra-ui/icon/dist/index.mjs", imported by "node_modules/chakra-react-select/dist/esm/chakra-components/menu.js".

### ISSUE THREAD

**Issue by Neno2113** [csandman/chakra-react-select#280] opened 2023-09-11 14:57 UTC
### Description

When I try to run the yarn build, it throws me an error related to the default import. in "node_modules/chakra-react-select/dist/esm/chakra-components/menu.js" this is not a problem. I could change the import but, the application crashes when running the Dockerfile

![Chakra-React-Select - Error](https://github.com/csandman/chakra-react-select/assets/19634134/b3505151-fbbe-42ec-ba6d-51d4f5efaf95)

### chakra-react-select Version

4.7.0

### TypeScript?

- [X] Yes I use TypeScript

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] iOS/iPadOS
- [ ] Android

**Comment by csandman** [comment] 2023-09-11 15:02
This is a duplicate of #276 which was fixed in [`v4.7.1`](https://github.com/csandman/chakra-react-select/releases/tag/v4.7.1) 6 minutes ago haha.

**Closed by csandman** 2023-09-11 15:02 UTC
Labels: Bug
