### ISSUE TITLE
Property "size" does not exist on type

### ISSUE THREAD

**Issue by bennyk8y** [csandman/chakra-react-select#278] opened 2023-09-09 12:56 UTC
### Description

```js
import { Select, useChakraSelectProps } from 'chakra-react-select';

function App() {
  return <Select size='sm' options=[{ label: 'blue' }, { label: 'green' }]/>;
}

```

There is no such prop of called "size". If ignoring this TS error, it accepts this prop and applies it correctly.

### chakra-react-select Version

4.7.0

### TypeScript?

- [X] Yes I use TypeScript

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS/iPadOS
- [ ] Android

**Comment by csandman** [comment] 2023-09-11 15:31
This appears to be a duplicate of #273 if I'm not mistaking. If it is, can close this and answer some of the questions I pose there to keep conversation centralized? I've still had no luck reproducing this issue.

**Closed** 2023-09-11 18:04 UTC
Labels: Bug
